package Views;

import Controller.FuncionarioController;
import Models.ContaBancaria;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 * <p>
 * Abre a tela de pesquisar clientes</p>
 *
 * @author Grupo 5 - LC IFTO
 */
public class TelaPesquisarClientes extends javax.swing.JFrame {

    /**
     * Creates new form FormTestte
     */
    public TelaPesquisarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisarCliente = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Clientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel1.setText("Pesquisar Clientes:");

        jTablePesquisarCliente.setAutoCreateRowSorter(true);
        jTablePesquisarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTablePesquisarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CONTA", "NOME", "AGÊNCIA", "CIDADE", "TIPO DA CONTA", "CPF", "STATUS CONTA", "STATUS CLIENTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePesquisarCliente.setToolTipText("");
        jTablePesquisarCliente.setAlignmentX(10.0F);
        jTablePesquisarCliente.setAlignmentY(10.0F);
        jTablePesquisarCliente.setGridColor(new java.awt.Color(0, 153, 153));
        jTablePesquisarCliente.setIntercellSpacing(new java.awt.Dimension(2, 1));
        jTablePesquisarCliente.setMaximumSize(new java.awt.Dimension(2147483647, 1));
        jTablePesquisarCliente.setMinimumSize(new java.awt.Dimension(75, 20));
        jTablePesquisarCliente.setRowHeight(24);
        jTablePesquisarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisarClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePesquisarCliente);
        if (jTablePesquisarCliente.getColumnModel().getColumnCount() > 0) {
            jTablePesquisarCliente.getColumnModel().getColumn(0).setMinWidth(75);
            jTablePesquisarCliente.getColumnModel().getColumn(0).setPreferredWidth(2);
            jTablePesquisarCliente.getColumnModel().getColumn(0).setMaxWidth(75);
            jTablePesquisarCliente.getColumnModel().getColumn(1).setMinWidth(250);
            jTablePesquisarCliente.getColumnModel().getColumn(1).setMaxWidth(250);
            jTablePesquisarCliente.getColumnModel().getColumn(2).setMinWidth(80);
            jTablePesquisarCliente.getColumnModel().getColumn(2).setMaxWidth(80);
            jTablePesquisarCliente.getColumnModel().getColumn(3).setMinWidth(185);
            jTablePesquisarCliente.getColumnModel().getColumn(3).setMaxWidth(185);
            jTablePesquisarCliente.getColumnModel().getColumn(4).setMinWidth(180);
            jTablePesquisarCliente.getColumnModel().getColumn(4).setMaxWidth(180);
            jTablePesquisarCliente.getColumnModel().getColumn(5).setMinWidth(120);
            jTablePesquisarCliente.getColumnModel().getColumn(5).setMaxWidth(120);
            jTablePesquisarCliente.getColumnModel().getColumn(6).setMinWidth(120);
            jTablePesquisarCliente.getColumnModel().getColumn(6).setMaxWidth(120);
        }

        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Sair");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1191, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if (!jTextField1.getText().trim().equals("") && jTextField1.getText().trim().length() > 1) {
            FuncionarioController.pesquisarClientes(jTablePesquisarCliente, jTextField1.getText().toUpperCase().trim());
        } else if (!jTextField1.getText().trim().equals("") && jTextField1.getText().trim().length() == 1 && jTextField1.getText().trim().equals("%")) {
            FuncionarioController.pesquisarClientes(jTablePesquisarCliente, jTextField1.getText().toUpperCase().trim());
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTablePesquisarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisarClienteMouseClicked

        // Quando o cliente clica duas vezes sobre a tabela, abre-se a TelaAlterarCliente 
        //Nessa tela, são preenchidos com os dados da linha selecionada na tabela jTablePesquisarCliente.
        try {
            if (evt.getClickCount() == 2) {
            
                int rowIndex = jTablePesquisarCliente.convertRowIndexToModel(jTablePesquisarCliente.getSelectedRow());

                TableModel model = jTablePesquisarCliente.getModel();

                //Primeiro Index da Tabela
                int conta = Integer.parseInt(model.getValueAt(rowIndex, 0).toString());

                String nome = model.getValueAt(rowIndex, 1).toString();

                String agencia = model.getValueAt(rowIndex, 2).toString();

                String cidade = model.getValueAt(rowIndex, 3).toString();

                String tipoDaConta = model.getValueAt(rowIndex, 4).toString();

                String statusConta = String.valueOf(model.getValueAt(rowIndex, 6));

                String statusCliente = String.valueOf(model.getValueAt(rowIndex, 7));

                //Verificar a documentação da Classe ContaBancaria
                ContaBancaria.setAgencia(agencia);
                ContaBancaria.setCidade(cidade);
                ContaBancaria.setNomeDoCliente(nome);
                ContaBancaria.setNumeroConta(conta);
                ContaBancaria.setTipoDaConta(tipoDaConta);
                ContaBancaria.setStatusConta(statusConta);
                ContaBancaria.setStatusCliente(statusCliente);

                new TelaAlterarCliente().setVisible(true);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção COD.4!", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jTablePesquisarClienteMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        /*if (!jTextField1.getText().equals("") && jTextField1.getText().length() > 1) {
            ClienteController.pesquisarFuncionarios(jTablePesquisarCliente, jTextField1.getText());
        } else if (!jTextField1.getText().equals("") && jTextField1.getText().length() == 1 && jTextField1.getText().equals("%")) {
            ClienteController.pesquisarFuncionarios(jTablePesquisarCliente, jTextField1.getText());
        }*/
    }//GEN-LAST:event_formWindowActivated

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPesquisarClientes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisarCliente;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
